repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [go]

      - id: test
        name: test
        entry: make test
        language: system
        types: [go]
