openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for focus
paths:
    /focus/tasks:
        get:
            tags:
                - task
            summary: list task
            description: List all tasks.
            operationId: task#list
            parameters:
                - name: parent_id
                  in: query
                  description: The ID of the parent task
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The ID of the parent task
                    example: Laboriosam quam repellendus cum.
                  example: Omnis a praesentium qui rerum quo maiores.
                - name: recursive
                  in: query
                  description: Whether to include all subtasks recursively
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: Whether to include all subtasks recursively
                    example: true
                  example: false
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskdetailCollection'
                            example:
                                - created_at: 338516047847680246
                                  id: Enim laboriosam quam veniam totam culpa.
                                  order: 0.909696535734263
                                  parent_id: Quia veniam recusandae aperiam quia.
                                  status: Voluptatem sequi iusto et sed corporis.
                                  title: Porro deleniti est.
                                - created_at: 338516047847680246
                                  id: Enim laboriosam quam veniam totam culpa.
                                  order: 0.909696535734263
                                  parent_id: Quia veniam recusandae aperiam quia.
                                  status: Voluptatem sequi iusto et sed corporis.
                                  title: Porro deleniti est.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - task
            summary: create task
            description: Create a new task.
            operationId: task#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskInput2'
                        example:
                            parent_id: Et quae omnis quia est.
                            title: Explicabo provident ut quis nesciunt perferendis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Taskdetail'
                            example:
                                created_at: 6895780904108519729
                                id: Iure provident enim ipsam cumque autem.
                                order: 0.9909283014974137
                                parent_id: Quaerat dolore id magnam ut ullam dolor.
                                status: Odio corporis animi praesentium.
                                title: Odio aut enim saepe voluptatem.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Internal server error
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        TaskInput:
            type: object
            properties:
                authorization:
                    type: string
                    description: The authorization header
                    example: Officia ut.
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Modi aut aut quae quia repellat deleniti.
                title:
                    type: string
                    description: The title of the task
                    example: Consequatur vel quia odit perferendis aut.
            example:
                authorization: Qui eum fugit repudiandae commodi beatae.
                parent_id: Maiores laudantium asperiores omnis eius.
                title: Repellendus commodi modi.
            required:
                - authorization
                - title
        TaskInput2:
            type: object
            properties:
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Praesentium beatae harum expedita consequuntur.
                title:
                    type: string
                    description: The title of the task
                    example: Et quasi.
            example:
                parent_id: Et eligendi accusamus at accusantium qui quod.
                title: Porro unde unde.
            required:
                - title
        Taskdetail:
            type: object
            properties:
                created_at:
                    type: integer
                    description: The timestamp when the task was created
                    example: 6866097796767887653
                    format: int64
                id:
                    type: string
                    description: The ID of the task
                    example: Error deserunt dolorem et totam.
                order:
                    type: number
                    description: The order of the task
                    example: 0.30744150741914367
                    format: double
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Quia et vel.
                status:
                    type: string
                    description: The status of the task
                    example: Nobis maiores in officiis provident ipsa impedit.
                title:
                    type: string
                    description: The title of the task
                    example: Nam architecto cumque optio fugit.
            example:
                created_at: 2235207784323695165
                id: Assumenda fuga.
                order: 0.47080858343358223
                parent_id: Corporis saepe unde beatae neque voluptatem.
                status: Autem distinctio molestiae harum aut enim temporibus.
                title: Omnis inventore minima alias.
            required:
                - id
                - title
                - created_at
                - status
                - order
        TaskdetailCollection:
            type: array
            items:
                $ref: '#/components/schemas/Taskdetail'
            example:
                - created_at: 338516047847680246
                  id: Enim laboriosam quam veniam totam culpa.
                  order: 0.909696535734263
                  parent_id: Quia veniam recusandae aperiam quia.
                  status: Voluptatem sequi iusto et sed corporis.
                  title: Porro deleniti est.
                - created_at: 338516047847680246
                  id: Enim laboriosam quam veniam totam culpa.
                  order: 0.909696535734263
                  parent_id: Quia veniam recusandae aperiam quia.
                  status: Voluptatem sequi iusto et sed corporis.
                  title: Porro deleniti est.
                - created_at: 338516047847680246
                  id: Enim laboriosam quam veniam totam culpa.
                  order: 0.909696535734263
                  parent_id: Quia veniam recusandae aperiam quia.
                  status: Voluptatem sequi iusto et sed corporis.
                  title: Porro deleniti est.
                - created_at: 338516047847680246
                  id: Enim laboriosam quam veniam totam culpa.
                  order: 0.909696535734263
                  parent_id: Quia veniam recusandae aperiam quia.
                  status: Voluptatem sequi iusto et sed corporis.
                  title: Porro deleniti est.
tags:
    - name: task
