swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
basePath: /focus
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /tasks:
        get:
            tags:
                - task
            summary: list task
            description: List all tasks.
            operationId: task#list
            parameters:
                - name: parent_id
                  in: query
                  description: The ID of the parent task
                  required: false
                  type: string
                - name: recursive
                  in: query
                  description: Whether to include all subtasks recursively
                  required: false
                  type: boolean
                - name: authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TaskTaskdetailResponseCollection'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TaskListInternalServerErrorResponseBody'
            schemes:
                - http
        post:
            tags:
                - task
            summary: create task
            description: Create a new task.
            operationId: task#create
            parameters:
                - name: authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TaskInput'
                    required:
                        - title
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Taskdetail'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TaskCreateInternalServerErrorResponseBody'
            schemes:
                - http
    /tasks/{task_id}:
        delete:
            tags:
                - task
            summary: delete task
            description: Delete a task.
            operationId: task#delete
            parameters:
                - name: task_id
                  in: path
                  description: The ID of the task
                  required: true
                  type: string
                - name: authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TaskDeleteInternalServerErrorResponseBody'
            schemes:
                - http
        patch:
            tags:
                - task
            summary: update task
            description: Update a task.
            operationId: task#update
            parameters:
                - name: task_id
                  in: path
                  description: The ID of the task
                  required: true
                  type: string
                - name: authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TaskUpdateInput'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Taskdetail'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TaskUpdateInternalServerErrorResponseBody'
            schemes:
                - http
definitions:
    TaskCreateInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal server error (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TaskDeleteInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Internal server error (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TaskInput:
        title: TaskInput
        type: object
        properties:
            parent_id:
                type: string
                description: The parent ID of the task
                example: Autem assumenda fuga et corporis.
            title:
                type: string
                description: The title of the task
                example: Unde beatae.
        example:
            parent_id: Voluptatem quisquam omnis.
            title: Minima alias impedit tempore.
        required:
            - title
    TaskListInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal server error (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TaskTaskdetailResponseCollection:
        title: 'Mediatype identifier: taskdetail; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/TaskdetailResponse'
        description: ListResponseBody is the result type for an array of TaskdetailResponse (default view)
        example:
            - actual_time: 2172334268853595857
              completed_at: 8789354938821462965
              created_at: 4811524684776275082
              estimated_time: 644087518531812643
              id: Corporis animi praesentium quasi occaecati quae.
              is_leaf: false
              lead_time: 5649253023867608586
              parent_id: Nisi qui ut corporis quia numquam.
              started_at: 8816741484794451297
              status: Aut omnis laborum eligendi repudiandae ratione quis.
              title: Beatae nobis.
            - actual_time: 2172334268853595857
              completed_at: 8789354938821462965
              created_at: 4811524684776275082
              estimated_time: 644087518531812643
              id: Corporis animi praesentium quasi occaecati quae.
              is_leaf: false
              lead_time: 5649253023867608586
              parent_id: Nisi qui ut corporis quia numquam.
              started_at: 8816741484794451297
              status: Aut omnis laborum eligendi repudiandae ratione quis.
              title: Beatae nobis.
            - actual_time: 2172334268853595857
              completed_at: 8789354938821462965
              created_at: 4811524684776275082
              estimated_time: 644087518531812643
              id: Corporis animi praesentium quasi occaecati quae.
              is_leaf: false
              lead_time: 5649253023867608586
              parent_id: Nisi qui ut corporis quia numquam.
              started_at: 8816741484794451297
              status: Aut omnis laborum eligendi repudiandae ratione quis.
              title: Beatae nobis.
    TaskUpdateInput:
        title: TaskUpdateInput
        type: object
        properties:
            estimated_time:
                type: integer
                description: The estimated time of the task
                example: 8956716131488875451
                format: int64
            parent_id:
                type: string
                description: The parent ID of the task
                example: Porro accusamus sunt sunt aliquid aliquid non.
            status:
                type: string
                description: The status of the task
                example: Alias est nulla eveniet earum.
            title:
                type: string
                description: The title of the task
                example: Doloribus modi ex qui ut eveniet.
        example:
            estimated_time: 2455952353529487638
            parent_id: Explicabo sed distinctio.
            status: Adipisci itaque a nisi quaerat rerum qui.
            title: Ab pariatur.
    TaskUpdateInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal server error (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    Taskdetail:
        title: 'Mediatype identifier: taskdetail; view=default'
        type: object
        properties:
            actual_time:
                type: integer
                description: The actual time of the task
                example: 3321688028374152550
                format: int64
            completed_at:
                type: integer
                description: The timestamp when the task was completed
                example: 3189980389450735329
                format: int64
            created_at:
                type: integer
                description: The timestamp when the task was created
                example: 8268824458518814376
                format: int64
            estimated_time:
                type: integer
                description: The estimated time of the task
                example: 6764894602263711702
                format: int64
            id:
                type: string
                description: The ID of the task
                example: Eveniet eaque iusto eum dolor.
            is_leaf:
                type: boolean
                description: Whether the task is a leaf task
                example: true
            lead_time:
                type: integer
                description: The lead time of the task
                example: 1552351292431645962
                format: int64
            parent_id:
                type: string
                description: The parent ID of the task
                example: Fugiat aut officia ut non modi aut.
            started_at:
                type: integer
                description: The timestamp when the task was started
                example: 1700675663212872878
                format: int64
            status:
                type: string
                description: The status of the task
                example: Odit perferendis aut voluptatem qui eum fugit.
            title:
                type: string
                description: The title of the task
                example: Quae quia repellat deleniti nihil consequatur vel.
        description: CreateResponseBody result type (default view)
        example:
            actual_time: 293339311425426817
            completed_at: 2835063725048473949
            created_at: 6063691705544486148
            estimated_time: 3594687342303680335
            id: Eius natus repellendus commodi.
            is_leaf: true
            lead_time: 6866097796767887653
            parent_id: Veritatis error deserunt.
            started_at: 2597680120660980244
            status: Et vel est nam.
            title: Et totam natus.
        required:
            - id
            - title
            - created_at
            - status
    TaskdetailResponse:
        title: 'Mediatype identifier: taskdetail; view=default'
        type: object
        properties:
            actual_time:
                type: integer
                description: The actual time of the task
                example: 7261730778451901492
                format: int64
            completed_at:
                type: integer
                description: The timestamp when the task was completed
                example: 1577758740305574389
                format: int64
            created_at:
                type: integer
                description: The timestamp when the task was created
                example: 3873497710463612547
                format: int64
            estimated_time:
                type: integer
                description: The estimated time of the task
                example: 5708883337736862485
                format: int64
            id:
                type: string
                description: The ID of the task
                example: Distinctio molestiae harum aut enim temporibus voluptas.
            is_leaf:
                type: boolean
                description: Whether the task is a leaf task
                example: false
            lead_time:
                type: integer
                description: The lead time of the task
                example: 7401243951852795824
                format: int64
            parent_id:
                type: string
                description: The parent ID of the task
                example: Praesentium beatae harum expedita consequuntur.
            started_at:
                type: integer
                description: The timestamp when the task was started
                example: 756885559405208355
                format: int64
            status:
                type: string
                description: The status of the task
                example: Et eligendi accusamus at accusantium qui quod.
            title:
                type: string
                description: The title of the task
                example: Et quasi.
        description: TaskdetailResponse result type (default view)
        example:
            actual_time: 5128894242372850282
            completed_at: 484763215522757662
            created_at: 2323846356294475801
            estimated_time: 2476647117455762088
            id: Culpa dolorem laudantium magnam.
            is_leaf: true
            lead_time: 7103049695158321830
            parent_id: Quam repellendus cum blanditiis omnis.
            started_at: 7464895724586063250
            status: Maiores odit recusandae et et.
            title: Praesentium qui rerum.
        required:
            - id
            - title
            - created_at
            - status
